In [1]:
from BaseAviary_Modquad import *

pybullet build time: Nov 14 2023 13:26:03


In [2]:
modquad = BaseAviary()

IndexError: child index out of range

In [18]:
def parseURDFParameters():
    """Loads parameters from an URDF file.

    This method is nothing more than a custom XML parser for the .urdf
    files in folder `assets/`.

    """
    # URDF_TREE = etxml.parse(pkg_resources.resource_filename('gym_pybullet_drones', 'assets/2x1_modquad/'+'2x1.urdf')).getroot()
    URDF_TREE = etxml.parse(pkg_resources.resource_filename('gym_pybullet_drones', 'assets/cf2p.urdf')).getroot()
    M = float(URDF_TREE[1][0][1].attrib['value'])
    
    L = float(URDF_TREE[0].attrib['arm'])
    THRUST2WEIGHT_RATIO = float(URDF_TREE[0].attrib['thrust2weight'])
    IXX = float(URDF_TREE[1][0][2].attrib['ixx'])
    IYY = float(URDF_TREE[1][0][2].attrib['iyy'])
    IZZ = float(URDF_TREE[1][0][2].attrib['izz'])
    J = np.diag([IXX, IYY, IZZ])
    J_INV = np.linalg.inv(J)
    KF = float(URDF_TREE[0].attrib['kf'])
    KM = float(URDF_TREE[0].attrib['km'])
    COLLISION_H = float(URDF_TREE[1][2][1][0].attrib['length'])
    COLLISION_R = float(URDF_TREE[1][2][1][0].attrib['radius'])
    COLLISION_SHAPE_OFFSETS = [float(s) for s in URDF_TREE[1][2][0].attrib['xyz'].split(' ')]
    COLLISION_Z_OFFSET = COLLISION_SHAPE_OFFSETS[2]
    MAX_SPEED_KMH = float(URDF_TREE[0].attrib['max_speed_kmh'])
    GND_EFF_COEFF = float(URDF_TREE[0].attrib['gnd_eff_coeff'])
    PROP_RADIUS = float(URDF_TREE[0].attrib['prop_radius'])
    DRAG_COEFF_XY = float(URDF_TREE[0].attrib['drag_coeff_xy'])
    DRAG_COEFF_Z = float(URDF_TREE[0].attrib['drag_coeff_z'])
    DRAG_COEFF = np.array([DRAG_COEFF_XY, DRAG_COEFF_XY, DRAG_COEFF_Z])
    DW_COEFF_1 = float(URDF_TREE[0].attrib['dw_coeff_1'])
    DW_COEFF_2 = float(URDF_TREE[0].attrib['dw_coeff_2'])
    DW_COEFF_3 = float(URDF_TREE[0].attrib['dw_coeff_3'])
    return M
    # return M, L, THRUST2WEIGHT_RATIO, J, J_INV, KF, KM, COLLISION_H, COLLISION_R, COLLISION_Z_OFFSET, MAX_SPEED_KMH, \
    #        GND_EFF_COEFF, PROP_RADIUS, DRAG_COEFF, DW_COEFF_1, DW_COEFF_2, DW_COEFF_3
parseURDFParameters()

<Element 'link' at 0x11fc413a0>


0.027

In [29]:
def parseURDFParameters():
    """Loads parameters from an URDF file.

    This method is nothing more than a custom XML parser for the .urdf
    files in folder `assets/`.

    """
    URDF_TREE = etxml.parse(pkg_resources.resource_filename('gym_pybullet_drones', 'assets/2x1_modquad/'+'2x1.urdf')).getroot()
    # URDF_TREE = etxml.parse(pkg_resources.resource_filename('gym_pybullet_drones', 'assets/cf2p.urdf')).getroot()
    M = float(URDF_TREE[1][0][2].attrib['value'])
    L = float(URDF_TREE[0].attrib['arm'])
    THRUST2WEIGHT_RATIO = float(URDF_TREE[0].attrib['thrust2weight'])
    IXX = float(URDF_TREE[1][0][1].attrib['ixx'])
    IYY = float(URDF_TREE[1][0][1].attrib['iyy'])
    IZZ = float(URDF_TREE[1][0][1].attrib['izz'])
    J = np.diag([IXX, IYY, IZZ])
    J_INV = np.linalg.inv(J)
    KF = float(URDF_TREE[0].attrib['kf'])
    KM = float(URDF_TREE[0].attrib['km'])
    COLLISION_H = float(URDF_TREE[3][1][1][0].attrib['length'])
    COLLISION_R = float(URDF_TREE[3][1][1][0].attrib['radius'])
    COLLISION_SHAPE_OFFSETS = [float(s) for s in URDF_TREE[1][1][0].attrib['xyz'].split(' ')]
    COLLISION_Z_OFFSET = COLLISION_SHAPE_OFFSETS[2]
    MAX_SPEED_KMH = float(URDF_TREE[0].attrib['max_speed_kmh'])
    GND_EFF_COEFF = float(URDF_TREE[0].attrib['gnd_eff_coeff'])
    PROP_RADIUS = float(URDF_TREE[0].attrib['prop_radius'])
    DRAG_COEFF_XY = float(URDF_TREE[0].attrib['drag_coeff_xy'])
    DRAG_COEFF_Z = float(URDF_TREE[0].attrib['drag_coeff_z'])
    DRAG_COEFF = np.array([DRAG_COEFF_XY, DRAG_COEFF_XY, DRAG_COEFF_Z])
    DW_COEFF_1 = float(URDF_TREE[0].attrib['dw_coeff_1'])
    DW_COEFF_2 = float(URDF_TREE[0].attrib['dw_coeff_2'])
    DW_COEFF_3 = float(URDF_TREE[0].attrib['dw_coeff_3'])
    return M, L, THRUST2WEIGHT_RATIO, J, J_INV, KF, KM, COLLISION_H, COLLISION_R, COLLISION_Z_OFFSET, MAX_SPEED_KMH, \
           GND_EFF_COEFF, PROP_RADIUS, DRAG_COEFF, DW_COEFF_1, DW_COEFF_2, DW_COEFF_3
parseURDFParameters()

(0.033750001341105,
 0.0397,
 2.25,
 array([[1.35000012e-04, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.68750015e-05, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 4.21875007e-05]]),
 array([[ 7407.40676123,     0.        ,     0.        ],
        [    0.        , 59259.25408984,     0.        ],
        [    0.        ,     0.        , 23703.70329162]]),
 3.16e-10,
 7.94e-12,
 0.0075362827628851,
 0.024999996647239,
 0.35,
 30.0,
 11.36859,
 0.0231348,
 array([9.1785e-07, 9.1785e-07, 1.0311e-06]),
 2267.18,
 0.16,
 -0.11)